In [1]:
import pyodbc

In [3]:
pyodbc.drivers()

['ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [4]:
# import libraries
import pyodbc # mssql
import pymysql # mySQL

from sqlalchemy import URL, create_engine

import pandas as pd

In [61]:
# MYSQLengine = create_engine('mysql+pymysql://root:password@127.0.0.1:3306/mydatabase?charset=utf8mb4&pool_pre_ping=True')

mysql_url = URL("mysql+pymysql", username='root', host='localhost', password='Uday@1102', port=3306, database='books', query={"charset":"utf8"})

In [62]:
# MSSQL
mssql_url = URL.create("mssql+pyodbc", username='VICTUS\\SQLEXPRESS',host='localhost', port=49716, database='testdb',query={"driver": pyodbc.drivers()[1],
    "Trusted_Connection":"yes",
    "Encrypt":"yes",
    "TrustServerCertificate":"yes"})

In [63]:
mysql_engine = create_engine(url=mysql_url)
mssql_engine = create_engine(url=mssql_url)

In [67]:
mysql_engine

Engine(mysql+pymysql://root:***@localhost:3306/books?charset=utf8)

In [64]:
mysql_engine, mssql_engine

(Engine(mysql+pymysql://root:***@localhost:3306/books?charset=utf8),
 Engine(mssql+pyodbc://VICTUS%5CSQLEXPRESS@localhost:49716/testdb?Encrypt=yes&TrustServerCertificate=yes&Trusted_Connection=yes&driver=ODBC+Driver+18+for+SQL+Server))

In [65]:
pd.read_sql("select * from test_table", mssql_engine)

    id   name
0  101  user1
1  102  user2

In [68]:
# pd.read_sql("select * from authors;", mysql_url)

In [69]:
df = pd.read_excel('../../Data/E-Commerce Orders.csv.xlsx')

In [70]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [71]:
df.to_sql('orders', mssql_engine)

88